Write-Host "Validating Smart Home MVP quickstart..."
Write-Host "1) Ensure backend is running on http://localhost:5151"
Write-Host "2) Ensure frontend is running on http://localhost:4200"
Write-Host "3) Ensure simulator is posting telemetry"
Write-Host "4) Verify /api/devices and /api/telemetry/latest endpoints respond"
